### ISSUE TITLE
Upgrade all dependencies to latest stable version

### ISSUE THREAD

**Issue by bstein** [NREL/OpenStudio-PAT#225]
This issue tracks the work of upgrading each dependency to its latest stable version.

### Phase 1 - Upgrade most `package.json` dependencies
- [x] ⏫ **[chalk](https://www.npmjs.com/package/chalk): ~1.1.0 → ~5.0.1**
- [x] ⏫ **[del](https://www.npmjs.com/package/del): ~2.2.0 → ~7.0.0**
- **[v7.0.0](https://github.com/sindresorhus/del/releases/tag/v7.0.0):** Package became pure ESM
    - [x] Use async `import('del')` instead of `gulp-load-plugins` ([more info](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c))
- [x] 🗑️ **[estraverse](https://www.npmjs.com/package/estraverse): ~4.2.0 → Remove since it is not used**
- [x] 🔼 **[electron](https://www.npmjs.com/package/electron): ~20.0.3 → ~20.1.3**
- [x] ⏫ **[fs-jetpack](https://www.npmjs.com/package/fs-jetpack): ~0.9.2 → ~4.3.1**
- [x] ⏫ **[gulp-angular-templatecache](https://www.npmjs.com/package/gulp-angular-templatecache): ~1.8.0 → ~3.0.1**
- [x] ⏫ **[gulp-autoprefixer](https://www.npmjs.com/package/gulp-angular-templatecache): ~3.1.0 → ~8.0.0**
- Started using `browserslist` configuration instead of `browsers` option
    - [x] Add `browserslist` configuration to `package.json` and remove `browsers` key/value from options when calling
- [x] ⏫ **[gulp-clean](https://www.npmjs.com/package/gulp-clean): ^0.3.2 → ~0.4.0**
- [x] ⏫ **[gulp-csso](https://www.npmjs.com/package/gulp-csso): ~1.1.0 → ~4.0.1**
- [x] ⏫ **[gulp-debug](https://www.npmjs.com/package/gulp-debug): ~2.1.2 → ~4.0.0**
    - [x] Move to `optionalDependencies`
- [x] ⏫ **[gulp-filter](https://www.npmjs.com/package/gulp-filter): 3.0.1 → ~7.0.0**
- [x] ⏫ **[gulp-flatten](https://www.npmjs.com/package/gulp-flatten): ~0.2.0 → ~0.4.0**
- [x] ⏫ **[gulp-htmlmin](https://www.npmjs.com/package/gulp-htmlmin): ~1.3.0 → ~5.0.1**
- [x] ⏫ **[gulp-inject](https://www.npmjs.com/package/gulp-inject): ~4.0.0 → ~5.0.5**
- [x] ⏫ **[gulp-load-plugins](https://www.npmjs.com/package/gulp-load-plugins): ~1.2.0 → ~2.0.8**
- [x] 🔼 **[gulp-ng-annotate](https://www.npmjs.com/package/gulp-ng-annotate): ~2.0.0 → ~2.1.0**
- [x] 🗑️ **[gulp-protractor](https://www.npmjs.com/package/gulp-protractor): ~2.2.0 → Remove since it is not used**
- [x] ⏫ **[gulp-rename](https://www.npmjs.com/package/gulp-rename): ~1.2.2 → ~2.0.0**
- [x] ⏫ **[gulp-replace](https://www.npmjs.com/package/gulp-replace): ~0.5.4 → ~1.1.3**
- [x] ⏫ **[gulp-rev](https://www.npmjs.com/package/gulp-rev): ~7.0.0 → ~9.0.0**
- [x] ⏫ **[gulp-rev-replace](https://www.npmjs.com/package/gulp-rev-replace): ~0.4.2 → ~0.4.4**
- [x] ⏫ **[gulp-size](https://www.npmjs.com/package/gulp-size): ~2.1.0 → ~4.0.1**
- [x] ⏫ **[gulp-sourcemaps](https://www.npmjs.com/package/gulp-sourcemaps): ~1.6.0 → ~3.0.0**
- **[v2.2.0](https://github.com/gulp-sourcemaps/gulp-sourcemaps/releases/tag/v2.2.0):** Started using `file.clone()` to create source map files
    - [x] Use `gulp-filter` to exclude `.map` files before piping to `gulp-rev-replace`
- [x] ➡️ **[gulp-streamify](https://www.npmjs.com/package/gulp-streamify): ^1.0.2 → ~1.0.2**
- [x] ⏫ **[gulp-uglify](https://www.npmjs.com/package/gulp-uglify): ~1.5.1 → ~3.0.2**
- [x] ⏫ **[gulp-useref](https://www.npmjs.com/package/gulp-useref): ~3.0.5 → ~5.0.0**
- [x] 🗑️ **[gulp-util](https://www.npmjs.com/package/gulp-util): ~3.0.6 → Remove since it is deprecated**
    - [x] Add **[fancy-log](https://www.npmjs.com/package/fancy-log)** and replace `util.log()` with `fancyLog()`
    - [x] Use **[chalk](https://www.npmjs.com/package/chalk)** and replace `util.colors` with `chalk`
    - [x] Use **[through2](https://www.npmjs.com/package/through2)** and replace `util.noop()` with `through2.obj()`
- [x] 🔼 **[lazypipe](https://www.npmjs.com/package/lazypipe): ~1.0.1 → ~1.0.2**
- [x] 🔼 **[lodash](https://www.npmjs.com/package/lodash): ~4.6.1 → ~4.17.21**
- [x] ⏫ **[merge-stream](https://www.npmjs.com/package/): ~1.0.0 → ~2.0.0**
- [x] 🔼 **[q](https://www.npmjs.com/package/q): ~1.4.1 → ~1.5.1**
- [x] 🔼 **[request](https://www.npmjs.com/package/request): ^2.75.0 → ~2.88.2**
- [x] ⏫ **[request-progress](https://www.npmjs.com/package/request-progress): ^2.0.1 → ~3.0.0**
- **[v3.0.0](https://github.com/IndigoUnited/node-request-progress/releases/tag/3.0.0):** `state.percentage` was removed
    - [x] Use `state.percent` instead of `state.percentage`
- [x] 🔼 **[sass](https://www.npmjs.com/package/sass): ~1.54.0 → ~1.54.9**
- [x] ⏫ **[through2](https://www.npmjs.com/package/through2): ~2.0.0 → ~4.0.2**
- [x] 🔼 **[tree-kill](https://www.npmjs.com/package/tree-kill): ~1.0.0 → ~1.2.2**
- [x] ⏫ **[yargs](https://www.npmjs.com/package/yargs): ^4.3.2 → ~17.5.1**

### Phase 2 - Upgrade `babel`, `eslint`, and `rollup` packages
**Upgrade to Babel 7 ([more info](https://babeljs.io/docs/en/v7-migration))**
- [x] 📦 **[babel-core](https://www.npmjs.com/package/babel-core)@~6.7.5 → [@babel/core](https://www.npmjs.com/package/@babel/core)@~7.19.1**
    - [x] Replace `.babelrc` file with `babel.config.json` file
    - [x] Add **[babel-plugin-angularjs-annotate](https://www.npmjs.com/package/babel-plugin-angularjs-annotate)** and include in `plugins` in `babel.config.json`
    - [x] Make any syntax changes necessary for compatibility (e.g., remove unused imports)
- [x] 📦 **[babel-eslint](https://www.npmjs.com/package/babel-eslint)@~6.0.0 → [@babel/eslint-parser](https://www.npmjs.com/package/@babel/eslint-parser)@~7.19.1**
    - [x] Update `parser` and set `parserOptions` in `.eslintrc` file
- [x] 📦 **[babel-preset-es2015-loose-rollup](https://www.npmjs.com/package/babel-preset-es2015-loose-rollup)@~7.0.0 → [@babel/preset-env](https://www.npmjs.com/package/@babel/preset-env)@~7.19.1**
    - [x] Include in `presets` in `babel.config.json` file

**Upgrade `eslint` packages**
- [x] ⏫ **[eslint-plugin-angular](https://www.npmjs.com/package/eslint-plugin-angular): ~1.0.0 → ~4.1.0**
    - [x] Update `plugins` to include `angular` in `.eslintrc` file
- [x] ⏫ **[eslint-plugin-lodash](https://www.npmjs.com/package/eslint-plugin-lodash): ~1.5.1 → ~7.4.0**
- [x] ⏫ **[gulp-eslint](https://www.npmjs.com/package/gulp-eslint): ~2.0.0 → ~6.0.0**

**Upgrade `rollup`**
- [x] ⏫ **[rollup](https://www.npmjs.com/package/rollup): ~0.34.1 → ~2.79.0**
    - [x] Refactor `bundle()` function in `./tasks/scripts.js` file to use newer syntax
- [x] 📦 **[rollup-plugin-babel](https://www.npmjs.com/package/rollup-plugin-babel)@~2.6.1 → [@rollup/plugin-babel](https://www.npmjs.com/package/@rollup/plugin-babel)@~5.3.1**
    - [x] Update babel import in `./tasks/scripts.js` file
    - [x] Set `babelHelpers: 'bundled'` in options when calling `babel()`

### Phase 3 - Upgrade non-angular `./app/package.json` dependencies
- [x] ⏫ **[adm-zip](https://www.npmjs.com/package/adm-zip): ~0.4.7 → ~0.5.9**
- [x] ⏫ **[archiver](https://www.npmjs.com/package/archiver): ~4.0.1 → ~5.3.1**
- [x] 🔼 **[bootstrap-sass](https://www.npmjs.com/package/bootstrap-sass): ~3.3.6 → ~3.4.3**
- [x] ⏫ **[fs-jetpack](https://www.npmjs.com/package/fs-jetpack): ~0.9.2 → ~4.3.1**
- [x] ⏫ **[jquery](https://www.npmjs.com/package/jquery): ~2.2.3 → ~3.6.1**
- **v3.0.0:** Deprecated `ready()` function
    - [x] Replace with equivalents ([more info](https://www.sitepoint.com/jquery-document-ready-plain-javascript/))
- [x] ⏫ **[js2xmlparser](https://www.npmjs.com/package/js2xmlparser): ~1.0.0 → ~4.0.2**
    - [x] Replace `js2xmlparser()` with `js2xmlparser.parse()`
- [x] 🔼 **[jszip](https://www.npmjs.com/package/jszip): ~3.1.1 → ~3.10.1**
- [x] 🔼 **[lodash](https://www.npmjs.com/package/lodash): ~4.12.0 → ~4.17.21**
- [x] 🗑️ **[openport](https://www.npmjs.com/package/openport): ~0.0.4 → Remove since it is deprecated**
    - [x] Add **[portfinder](https://www.npmjs.com/package/portfinder)** and replace `openport.find()` with `portfinder.getPort()`
- [x] ⏫ **[xml2js](https://www.npmjs.com/package/xml2js): ~0.4.16 → ~0.4.23**
- [x] ⏫ **[yamljs](https://www.npmjs.com/package/yamljs): ~0.2.8 → ~0.3.0**

### Phase 4 - Upgrade angular `./app/package.json` dependencies
- [x] 🔼 **[angular](https://www.npmjs.com/package/angular): ~1.5.5 → ~1.8.3**
- **[v1.6.0](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#160-rainbow-tsunami-2016-12-08):** Removed `$http`'s custom callback functions `success()` and `error()`
    - [x] Replace with standard `then()` / `catch()` promise methods ([more info](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#http-due-to))
- **[v1.6.0](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#170-nonexistent-physiology-2018-05-11):** The default hash prefix changed from empty string "" to the bang "!"
    - [x] Explicitly set no hash prefix
- **[v1.7.0](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#160-rainbow-tsunami-2016-12-08):** `$interval.cancel()` now throws an error if called with a promise that was not generated by `$interval()`.
    - [x] In `runController.js`: Remove `$interval.cancel()` call and just set `vm.getStatus` to `undefined` instead
- [x] 🔼 **[angular-animate](https://www.npmjs.com/package/angular-animate): ~1.5.5 → ~1.8.3**
- [x] 🔼 **[angular-aria](https://www.npmjs.com/package/angular-aria): ~1.5.5 → ~1.8.3**
- [x] 🔼 **[angular-messages](https://www.npmjs.com/package/angular-messages): ~1.5.5 → ~1.8.3**
- [x] 🔼 **[angular-resource](https://www.npmjs.com/package/angular-resource): ~1.5.5 → ~1.8.3**
- [x] 🔼 **[angular-sanitize](https://www.npmjs.com/package/angular-sanitize): ~1.5.5 → ~1.8.3**
- [x] ⏫ **[angular-toastr](https://www.npmjs.com/package/angular-toastr): ~1.7.0 → ~2.1.1**
- **[v2.0.0](https://github.com/Foxandxss/angular-toastr/blob/master/CHANGELOG.md#version-200):** The `toast` styles are no longer automatically applied
    - [x] Update `toastClass` to include `toast` in `index.config.js`
- [x] 🔼 **[angular-translate](https://www.npmjs.com/package/angular-translate): ~2.11.0 → ~2.19.0**
- [x] 🔼 **[angular-translate-handler-log](https://www.npmjs.com/package/angular-translate-handler-log): ~2.11.0 → ~2.19.0**
- [x] ⏫ **[angular-ui-bootstrap](https://www.npmjs.com/package/angular-ui-bootstrap): ~1.5.5 → ~2.5.6**
- **[v2.0.0](https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md#200-2016-07-20):** The `<uib-accordion-group ... />` element is now only available via the `uib-accordion-group` directive
    - [x] Replace `<uib-accordion-group ... />` elements with `<div uib-accordion-group ... />` ([more info](https://stackoverflow.com/a/38489803))
    - [x] Add `panel-default` class, since it is no longer automatically applied when using the directive
- [x] 🔼 **[angular-ui-grid](https://www.npmjs.com/package/angular-ui-grid): 4.0.2 → ~4.11.1**
- [x] ⏫ **[angular-ui-router](https://www.npmjs.com/package/angular-ui-router): ~0.2.18 → ~1.0.30**
- When calling `$state.transitionTo()` in order to reload the analysis page after setting the project, the following error is thrown: `Transition Rejection($id: 0 type: 2, message: The transition has been superseded by a different transition, detail: Transition#2( 'analysis'{} -> 'analysis'{} ))`
    - [x] Wrap the `$state.transitionTo()` call in `$timeout()` so the transition only starts after current processes finish ([more info](https://stackoverflow.com/a/54075402))
- [x] 🔼 **[ui-grid-draggable-rows](https://www.npmjs.com/package/ui-grid-draggable-rows): ~0.3.2 → ~0.3.3**
